apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: kube
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: nginx
      port: 80
      nodePort: 30003
      targetPort: 80